TRUNCATE TABLE "RealBetLog" CASCADE;
TRUNCATE TABLE "Bet" CASCADE;
TRUNCATE TABLE "Signal" CASCADE;
TRUNCATE TABLE "OddsHistory" CASCADE;
TRUNCATE TABLE "Odds" CASCADE;
TRUNCATE TABLE "Match" CASCADE;
